version: '3'

services:
    web:
        image: nginx:latest
        container_name: app_nginx
        ports:
            - "8080:80"

        volumes:
            - ./code:/code
            - ./site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - app-network
    php:
        build:
            context: .
            dockerfile: PHP.Dockerfile
        container_name: app_php
        image: php:8.0.0-fpm
        volumes:
            - ./code:/code
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
